version: '3.8'

services:
  web1:
    build: src
    volumes:
      - .:/app
    environment:
      SERVER_ID: SERVER-1
      REDIS_HOST: redis   # Add Redis host
      REDIS_PORT: 6379    # Add Redis port
    depends_on:
      - redis             # Ensure Redis starts before the web service
    networks:
      - webnet

  web2:
    build: src
    volumes:
      - .:/app
    environment:
      SERVER_ID: SERVER-2
      REDIS_HOST: redis   # Add Redis host
      REDIS_PORT: 6379    # Add Redis port
    depends_on:
      - redis             # Ensure Redis starts before the web service
    networks:
      - webnet

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2
    networks:
      - webnet

networks:
  webnet:
